In [64]:
import numpy as np

# Q6
X = np.array([[6.1,2.2],[3.4,3.7]])
u1 = np.array([1,1])

gamma = np.array([[0.8], [0.2]])
N1 = sum(gamma)
x_cent = X - u1
print(x_cent)
print(x_cent@x_cent.T)
covar1 = gamma.T@x_cent@x_cent.T
covar1

[[5.1 1.2]
 [2.4 2.7]]
[[27.45 15.48]
 [15.48 13.05]]


array([[25.056, 14.994]])

In [50]:
print(gamma)

[0.8 0.2]


In [6]:
def eval_2d_gauss(x,y,u_x,u_y,s_x,s_y):
    answ = 1.0/(2*np.pi*s_x*s_y)*np.exp(-0.5*(((x-u_x)/s_x)**2+((y-u_y)/s_y)**2))
    return answ

In [42]:
# Q8
one = np.array([[1], [1]])
I = np.eye(2,2) + 1e-12
ans1 = eval_2d_gauss(0, 0,1, 1, 1, 1)
print(ans1)
n1 = 0.5 *ans1
print(n1)
ans2 = eval_2d_gauss(0, 0,-2, -2, 1, 1)
print(ans2)
n2 = 0.5 * ans2
print(n2)
gamma1 = n1/(n1+n2)
print("Gamma 1: ", gamma1 )

0.05854983152431917
0.029274915762159584
0.0029150244650281935
0.0014575122325140967
Gamma 1:  0.9525741268224333


In [31]:
#Q10
X = np.array([1, 1, 2, 3, 5, 8, 13, 21, 33, 54])

dist1 = abs(X - 0)
dist2 = abs(X - 11)
print("Distance 1: ", dist1)
print("Distance 2: ", dist2)

new_mean_1 =  (1 + 1 + 2 + 3 + 5)/5
new_mean_2 = (8 + 13 + 21 + 33 + 54)/5
print("Mean 1: ", new_mean_1)
print("Mean 2: ", new_mean_2)
dist1 = abs(X - new_mean_1)
dist2 = abs(X - new_mean_2)
print("Distance 1: ", dist1)
print("Distance 2: ", dist2)
new_mean_1 = (1 + 1 + 2 + 3 + 5 + 8 + 13)/7
new_mean_2 = (21 + 33 + 54)/3
print("Mean 1: ", new_mean_1)
print("Mean 2: ", new_mean_2)

Distance 1:  [ 1  1  2  3  5  8 13 21 33 54]
Distance 2:  [10 10  9  8  6  3  2 10 22 43]
Mean 1:  2.4
Mean 2:  25.8
Distance 1:  [ 1.4  1.4  0.4  0.6  2.6  5.6 10.6 18.6 30.6 51.6]
Distance 2:  [24.8 24.8 23.8 22.8 20.8 17.8 12.8  4.8  7.2 28.2]
Mean 1:  4.714285714285714
Mean 2:  36.0
