In [27]:
# 5)
import numpy as np
def sigmoid(z):
    return 1 / (1 + np.exp(-z))
X = np.array([[1, 9, 5],[3, 3, 5],[0.7, 0.9, 0.2]])
w = np.array([1, 1, 1])

In [35]:
lambda_H = 1
sig = sigmoid(w.T @ X)
weights = sig * (1 - sig)
I = np.eye(3,3)
H = (X * weights) @ X.T + (1/lambda_H)*I
print(H)

[[1.01006359 0.02779281 0.00630984]
 [0.02779281 1.0813402  0.01880124]
 [0.00630984 0.01880124 1.00438022]]


In [36]:
# 9)
import numpy as np
X = np.array([[1,9,5],[3,3,5],[0.7,0.9,0.2]])
w = np.array([1,1,1])
y = np.array([0,1,0])

In [54]:
lambda_m = 1
# m=∇l=−∑n=1N(yn−σ(wTxn))xn+1λw
sig = sigmoid(w.T @ X)
weights = y - sig
gradient_data = -(X @ weights)
m = gradient_data + (1 / lambda_m) * w
print(m)

[6.99077837 8.97276677 1.89368101]
