In [1]:
import numpy as np

In [ ]:
# 9 (features) x 11 (observations)




In [14]:
#q4:
from logistic_math import sigmoid
import numpy as np
X = np.array([[1, 9, 5],[3, 3, 5],[0.7, 0.9, 0.2]])
w = np.array([1,1,1])
y = np.array([0,1,0])


lambda_4 = 1

l = -np.sum(y@np.log(sigmoid(w.T@X)) + (1-y)@np.log(1-sigmoid(w.T@X))) + (1/(2*lambda_4))*w.T@w
print(l)

           

16.40909383184395


In [70]:
import numpy as np
from logistic_math import sigmoid
X = np.array([[1, 9, 5],[3, 3, 5],[0.7, 0.9, 0.2]])
w = np.array([1, 1, 1])
I = np.eye(3,3)
H = sigmoid(w.T@X)@(1-sigmoid(w.T@X))
H = np.sum(H*X@X.T) + I
print(H)

[[3.62458834 2.62458834 2.62458834]
 [2.62458834 3.62458834 2.62458834]
 [2.62458834 2.62458834 3.62458834]]


In [79]:
#q8

X = np.array([[11,7,5,3],[1,2,3,1]])
y = np.array([1,2,1,2])
print(X[0,3])

3


In [83]:
X = np.array([[1,9,5],[3,3,5],[0.7,0.9,0.2]])
w = np.array([1,1,1])
y = np.array([0,1,0])


m = -np.sum((y-sigmoid(w.T@X))@X) + w
print(m)

[17.66470614 17.66470614 17.66470614]
