# Comprehensive NumPy Tutorial
Run each cell sequentially to observe the outputs and interact with the data.
Modify the variables in the `Testing Segment` of each section to verify your understanding.

## 1. Array Creation
NumPy's core object is the `ndarray` (n-dimensional array).

In [5]:
import numpy as np
print(f"NumPy Version: {np.__version__}")

# From standard Python lists
list_1d = [1, 2, 3, 4, 5]
arr_1d = np.array(list_1d)

list_2d = [[1, 2, 3], [4, 5, 6]]
arr_2d = np.array(list_2d)

# Built-in creation functions
zeros_arr = np.zeros((3, 3))       # 3x3 matrix of zeros
ones_arr = np.ones((2, 4))         # 2x4 matrix of ones
arange_arr = np.arange(0, 10, 2)   # Start, stop (exclusive), step
linspace_arr = np.linspace(0, 1, 5) # 5 evenly spaced numbers between 0 and 1
random_arr = np.random.rand(2, 2)  # 2x2 matrix of random uniform [0, 1) values

print("1D Array:\n", arr_1d)
print("2D Array:\n", arr_2d)
print("Zeros:\n", zeros_arr)
print("Arange:\n", arange_arr)

# --- Testing Segment 1 ---
# TODO: Create a 3x3 array of the number 7 using np.full()
test_arr_1 = np.full((3,3),7 )
print(test_arr_1)

NumPy Version: 2.4.2
1D Array:
 [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Arange:
 [0 2 4 6 8]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


## 2. Array Attributes
Inspecting the shape, size, and data types of arrays.

In [7]:
sample_arr = np.array([[1.5, 2.5, 3.5], [4.5, 5.5, 6.5]])

print("Array:\n", sample_arr)
print("Dimensions (ndim):", sample_arr.ndim)
print("Shape:", sample_arr.shape)       # (rows, columns)
print("Total elements (size):", sample_arr.size)
print("Data type (dtype):", sample_arr.dtype)

# --- Testing Segment 2 ---
# TODO: Check the attributes of a 3D array
test_arr_2 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Shape:", test_arr_2.shape)
print("Dimensions:", test_arr_2.ndim)
print("Data type:", test_arr_2.dtype)
print("Size:", test_arr_2.size)

Array:
 [[1.5 2.5 3.5]
 [4.5 5.5 6.5]]
Dimensions (ndim): 2
Shape: (2, 3)
Total elements (size): 6
Data type (dtype): float64
Shape: (2, 2, 2)
Dimensions: 3
Data type: int64
Size: 8


## 3. Indexing and Slicing
Accessing specific elements or subarrays. Python uses 0-based indexing.

In [11]:
idx_arr = np.arange(10, 20)
print("Base Array:", idx_arr)
print("Index 0:", idx_arr[0])
print("Last element:", idx_arr[-1])
print("Slice [2:5]:", idx_arr[2:5])

idx_arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("\nBase 2D Array:\n", idx_arr_2d)
print("Element at row 1, col 2:", idx_arr_2d[1, 2])
print("First row:", idx_arr_2d[0, :])
print("First column:", idx_arr_2d[:, 0])
print("Sub-matrix (top-right 2x2):\n", idx_arr_2d[0:2, 1:3])

# --- Testing Segment 3 ---
# TODO: Extract the bottom-left 2x2 sub-matrix from idx_arr_2d
test_slice = idx_arr_2d[1:3,0:2]
print("Test Slice:\n", test_slice)

Base Array: [10 11 12 13 14 15 16 17 18 19]
Index 0: 10
Last element: 19
Slice [2:5]: [12 13 14]

Base 2D Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at row 1, col 2: 60
First row: [10 20 30]
First column: [10 40 70]
Sub-matrix (top-right 2x2):
 [[20 30]
 [50 60]]
Test Slice:
 [[40 50]
 [70 80]]


## 4. Advanced Indexing (Boolean & Fancy)
Selecting elements based on conditions or specific index arrays.

In [17]:
adv_arr = np.arange(1, 11)
print("Base Array:", adv_arr)

# Boolean Indexing (Masking)
mask = adv_arr > 5
print("Mask (val > 5):", mask)
print("Filtered Array:", adv_arr[mask])
print("Even numbers only:", adv_arr[adv_arr % 2 == 0])

# Fancy Indexing
indices = [0, 3, 8] # 1st, 4th, and 9th elements
print("Elements at specific indices:", adv_arr[indices])

# --- Testing Segment 4 ---
# TODO: Find all elements in idx_arr_2d (from Section 3) that are strictly greater than 40
test_mask_result = idx_arr_2d[idx_arr_2d > 40]
print("Values > 40:", test_mask_result)

Base Array: [ 1  2  3  4  5  6  7  8  9 10]
Mask (val > 5): [False False False False False  True  True  True  True  True]
Filtered Array: [ 6  7  8  9 10]
Even numbers only: [ 2  4  6  8 10]
Elements at specific indices: [1 4 9]
Values > 40: [50 60 70 80 90]


## 5. Operations and Broadcasting
NumPy allows vectorized operations without explicit loops.

In [19]:
op_arr1 = np.array([1, 2, 3])
op_arr2 = np.array([10, 20, 30])

print("Addition:", op_arr1 + op_arr2)
print("Multiplication:", op_arr1 * op_arr2)
print("Scalar Multiplication:", op_arr1 * 5)
print("Power:", op_arr1 ** 2)

# Broadcasting: Applying operations on arrays of different shapes
scalar = 10
print("\nBroadcasting a scalar:\n", op_arr1 + scalar)

matrix = np.array([[10, 20, 30], [40, 50, 60]])
vector = np.array([1, 2, 3])
print("\nBroadcasting a vector to a matrix:\n", matrix + vector)

# --- Testing Segment 5 ---
# TODO: Multiply a 3x1 column vector by a 1x3 row vector to create a 3x3 matrix
col_vec = np.array([[1], [2], [3]])
row_vec = np.array([4, 5, 6])
test_broadcast = col_vec * row_vec
print("Broadcast Matrix:\n", test_broadcast)

Addition: [11 22 33]
Multiplication: [10 40 90]
Scalar Multiplication: [ 5 10 15]
Power: [1 4 9]

Broadcasting a scalar:
 [11 12 13]

Broadcasting a vector to a matrix:
 [[11 22 33]
 [41 52 63]]
Broadcast Matrix:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


## 6. Aggregation and Statistics
Computing summary statistics along different axes.

In [23]:
stat_arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Base Array:\n", stat_arr)

print("Sum of all elements:", stat_arr.sum())
print("Mean of all elements:", stat_arr.mean())
print("Max value:", stat_arr.max())

print("\nSum along axis 0 (column sum):", stat_arr.sum(axis=0))
print("Mean along axis 1 (row mean):", stat_arr.mean(axis=1))

# --- Testing Segment 6 ---
# TODO: Find the minimum value in each column of stat_arr
test_min_cols = stat_arr.min(axis=0)
print("Min of columns:", test_min_cols)

Base Array:
 [[1 2 3]
 [4 5 6]]
Sum of all elements: 21
Mean of all elements: 3.5
Max value: 6

Sum along axis 0 (column sum): [5 7 9]
Mean along axis 1 (row mean): [2. 5.]
Min of columns: [1 2 3]


## 7. Array Manipulation (Reshaping & Stacking)
Changing array structures without changing the underlying data.

In [25]:
manip_arr = np.arange(1, 13)
print("Original 1D:", manip_arr)

# Reshape
reshaped_arr = manip_arr.reshape(3, 4)
print("\nReshaped to 3x4:\n", reshaped_arr)

# Flatten
flat_arr = reshaped_arr.flatten()
print("\nFlattened back to 1D:", flat_arr)

# Stacking arrays
a = np.array([1, 2])
b = np.array([3, 4])
print("\nVertical Stack:\n", np.vstack((a, b)))
print("Horizontal Stack:\n", np.hstack((a, b)))

# --- Testing Segment 7 ---
# TODO: Reshape manip_arr into a 3D array with shape (2, 2, 3)
test_reshape_3d = manip_arr.reshape(2,2,3)
print("3D Reshape:\n", test_reshape_3d)

Original 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flattened back to 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Vertical Stack:
 [[1 2]
 [3 4]]
Horizontal Stack:
 [1 2 3 4]
3D Reshape:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 8. Basic Linear Algebra
Matrix dot products, transpositions, and solving systems.

In [28]:
mat_A = np.array([[1, 2], [3, 4]])
mat_B = np.array([[5, 6], [7, 8]])

# Matrix Multiplication (Dot Product)
print("Dot Product (np.dot):\n", np.dot(mat_A, mat_B))
print("Dot Product (@ operator):\n", mat_A @ mat_B)

# Transpose
print("\nTranspose of A:\n", mat_A.T)

# Inverse
inverse_A = np.linalg.inv(mat_A)
print("\nInverse of A:\n", inverse_A)

print("\nA @ A_inv (Should be Identity):\n", np.round(mat_A @ inverse_A))

# --- Testing Segment 8 ---
# TODO: Calculate the determinant of mat_B using np.linalg.det
test_det_B = np.linalg.det(mat_B)
print("Determinant of B:", test_det_B)

Dot Product (np.dot):
 [[19 22]
 [43 50]]
Dot Product (@ operator):
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

A @ A_inv (Should be Identity):
 [[1. 0.]
 [0. 1.]]
Determinant of B: -2.000000000000005
